name: Issue Management

on:
  workflow_call:

env:
  PROJECT_ID: 1
  TRIAGE_LABEL: needs-triage

jobs:
  manage_incoming_issues:
    name: Manage incoming issues
    if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
    runs-on: ubuntu-latest
    concurrency: issue_labels-${{ github.event.issue.number }}
    permissions:
      issues: write
    steps:
        - run: |
            # make sure that label exists
            gh label --repo ${{ github.event.repository.full_name }} create -f ${{ env.TRIAGE_LABEL }} -c 000000 -d "Issue needs triage"
            # add label to issue
            gh issue --repo ${{ github.event.repository.full_name }} edit ${{ github.event.issue.html_url }} --add-label ${{ env.TRIAGE_LABEL }}
            # add issue to the project
            gh project item-add ${{ env.PROJECT_ID }} --owner ${{ github.event.organization.login }} --url ${{ github.event.issue.html_url }}
          env:
            # token needs to have read/write permision for projects on org level and issues on repo level
            GH_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
